services:
  tg_bot:
    build: ./tg_bot
    networks:
      - dev

  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "AGRONOM"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

networks:
  dev:

volumes:
  postgres_data:

